### ISSUE TITLE
better to add the cron job

### ISSUE THREAD

**Issue by LarryZhang** [piwik/docker-piwik#77]
better to add the cron job

**Comment by crazy-max** [comment]
@LarryZhang I have added a cron job in my Docker image of Matomo if you are interested : https://github.com/crazy-max/docker-matomo

**Comment by J0WI** [comment]
You don't need cron in Docker containers. Just use cron or systemd timers on your host system that executes something like `docker exec -u www-data some-piwik php console`.

**Comment by Silvenga** [comment]
To follow Docker best practices, it would be best to have a sidecar container to handle cron like events - https://docs.microsoft.com/en-us/azure/architecture/patterns/sidecar.

**Comment by sagebind** [comment]
This is the main reason why I've been maintaining my own Matomo images; the recommended approaches here don't work in a setup like Docker Swarm.

* Running cron on the host system is not a reasonable solution. In a swarm, the host is a swarm node, with just Docker installed. Nodes can be created and deleted at any time and do not know which services will be run on them.
* Sidecar also is not a good solution. To run the archive from the console, the sidecar would have to have access to PHP (preferably same version as the main container), all the PHP class files in the app, and the configs. Configs may be in a volume, but the app code isn't.

Alternative would be to run a sidecar that hits the URL endpoint at regular intervals to perform archiving. That would work, but Matomo's own website recommends using the URL endpoint only as a last resort:

> If possible, we highly recommend that you run a cron or scheduled task. However, on some shared hosting, or on particular server configurations, running a cron or scheduled task may not be easy or possible.
>
> -- https://matomo.org/docs/setup-auto-archiving/

**Comment by crazy-max** [comment]
@sagebind Here is a swarm compose if you want to take a look : https://github.com/crazy-max/docker-matomo/blob/master/examples/swarm/docker-compose.yml
The cron solution uses [swarm-cronjob](https://github.com/crazy-max/swarm-cronjob)

**Comment by rvalle** [comment]
I agree with @Silvenga regarding the side-car pattern, but I am also interested in swarm implications.

@sagebind is it not possible to use swarm placement constrains to ensure that the cron sidecar is run next to the matomo container?

AFAIK the cron sidecar needs to mount the volume where php code is and also needs network access to the database. I assume that we are talking here about access to that php volume, right? matomo is already recommending to use a volume for the php code.

To me, I would find helpful if this image came with cron installed (but not running), so that the same image can be used for app (like now) and cron  sidecar: i.e. php version is the same, etc. An alternative entrypoint can then be used (cron -f) that will run the cron in foreground.  

At least this fixes the problem for deployments on a docker host, and maybe swarm if placement constraints can make the containers run side by side.

**Comment by J0WI** [comment]
> To me, I would find helpful if this image came with cron installed

[Busybox](https://hub.docker.com/_/busybox), which is already included in the Alpine variant, ships with a cron daemon.

**Comment by sagebind** [comment]
To this day, the only way in Swarm to pin two containers to the same node is to pin both to a _specific_ node, which is unacceptable for high availability.

The Kubernetes solution is to put both containers in the same pod.

**Comment by fareszr** [comment]
hi i am currently running the apache verison what do i have to do to add cron support ??

adding this did not work:

```
  cron:
    image: matomo:fpm
    links:
      - db
    volumes:
      - ./config:/var/www/html/config
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
```

**Comment by pschichtel** [comment]
I would be great if the image would just have crond and an appropriate configuration, that way you could just run crond from the same image in a separate container. This is how many other images do it (e.g. nextcloud).

**Comment by gardner** [comment]
Having cron baked into the image is an anti-pattern for docker. Having every node in a swarm or ECS cluster trying to run the archive task every 5 minutes would be a nightmare.

The [docker-compose.yml](https://github.com/crazy-max/docker-matomo/blob/master/examples/swarm/docker-compose.yml) that @crazy-max linked is a good solution.

**Comment by pschichtel** [comment]
The suggestion was to have the crond binary and config in there, but not actually running it. They way you can use the same container with different commands for the cronjob and the actual application

**Comment by J0WI** [comment]
The Alpine variant contains BusyBox with the [crond applet](https://www.busybox.net/downloads/BusyBox.html#crond). You can mount a cron file into `/var/spool/cron/crontabs` and start a container with `busybox crond -f`.

**Comment by noahsbwilliams** [comment]
I'd like to second what @rule88 said.

In Kubernetes, Heroku, or other "container only" environments, users are forced to either maintain their own images (bad for security) or use a hack like this (opaque, difficult to maintain).

Both can be avoided by including a minimal shell script in the image which can be set as the `entrypoint`. In practice, all the end user would have to do to properly setup cron is add a service like this:

```yaml
cron:
  image: matomo:apache
  volumes:
    - matomo:/var/www/html
  entrypoint: /cron.sh
```

**Comment by williamdes** [comment]
I added a service

```yaml

  matomo-fpm-cron:
    image: matomo:fpm-alpine
    restart: always
    network_mode: host
    entrypoint: sh -c 'echo "running..." && busybox crond -L /dev/stdout -f && echo "stop"'
    volumes:
      - matomo:/var/www/html
      - ./crontab:/var/spool/cron/crontabs/root:ro
    environment:
      MATOMO_DATABASE_HOST: ${MATOMO_DATABASE_HOST}
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX: matomo_
      MATOMO_DATABASE_USERNAME: ${MATOMO_DATABASE_USERNAME}
      MATOMO_DATABASE_PASSWORD: ${MATOMO_DATABASE_PASSWORD}
      MATOMO_DATABASE_DBNAME: ${MATOMO_DATABASE_DBNAME}
```
Here is the contents of my `./crontab` file: `*/20 * * * * /usr/local/bin/php /var/www/html/console scheduled-tasks:run`

Logs:
```
running...
crond: crond (busybox 1.33.1) started, log level 8
crond: USER root pid   8 cmd /usr/local/bin/php /var/www/html/console scheduled-tasks:run
INFO [2021-08-24 16:40:00] 8  Starting Scheduled tasks... 
INFO [2021-08-24 16:40:00] 8  done

Scheduled Tasks executed
```

**Comment by rule88** [comment]
My repo which includes the `cron` approach with a while-with-sleep-loop: https://github.com/rule88/matamo/

**Comment by fengerzh** [comment]
I tried to use cronjob in container, but it does not work, so I have to use a seperate container to run the cron job, but it seems the `tempfs` not work either, and I don't know why must made the volume read only to cron container, so I just made a simple container like below and it works.

```
version: "3"

services:
  matomodb:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - matomodb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=password
    env_file:
      - ./db.env

  app:
    image: matomo
    restart: always
    volumes:
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=matomodb
    env_file:
      - ./db.env
    ports:
      - 3780:80

  cron:
    image: matomo
    restart: always
    volumes:
      - matomo:/var/www/html
    depends_on:
      - app
    entrypoint: "sh -c 'while true; do php console core:archive --url=https://mat.yourdomain.com/; sleep 3600; done'"

volumes:
  matomodb:
  matomo:
```

**Comment by cedricverhaeghe** [comment]
My solution for this is to use [ofelia](https://github.com/mcuadros/ofelia)

In my setup I have an extra container in my Docker Compose file which runs the task as `www-data` user in the `app` container periodically.

docker-compose.yml:
```
...
  ofelia:
    image: mcuadros/ofelia:v0.3.6
    restart: always
    depends_on:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia/config.ini:/etc/ofelia/config.ini
 ...
```

ofelia/config.ini:
```
[job-exec "job-archive-reports"]
schedule = @every 1h
container = matomo-app-1
command = /usr/local/bin/php /var/www/html/console core:archive --url=http://your.domain.com
user = www-data
tty = true
```

**Comment by ctueck** [comment]
In case it helps anyone else, I made a very simple derived cron image so that I can have the schedule in environment variables and don't need to mount the crontab. As we use the Alpine-based image it can simply use the busybox crond. (In addition, I added a wait loop not to run cronjobs on an instance not yet set up.)

Dockerfile:
```Dockerfile
# start from Matomo official image
FROM matomo:4-fpm-alpine

# add cron entrypoint
ADD entrypoint.cron.sh /

ENTRYPOINT [ "/entrypoint.cron.sh" ]

CMD [ "crond", "-f", "-d6" ]
```

entrypoint.cron.sh:
```sh
#!/bin/sh

# timeout - configured in .env or defaults
[ -n "$WAIT_STEP" ] || WAIT_STEP=5 # seconds
[ -n "$WAIT_MAX" ]  || WAIT_MAX=60 # x WAIT_STEP seconds

echo -n "Creating crontab for www-data..."

crontab -u root -r
crontab -u www-data - << EOF
${CRON_ARCHIVE} /var/www/html/console core:archive
${CRON_TASKS} /var/www/html/console scheduled-tasks:run
EOF

echo " done."

# wait for matomo instance to be configured
echo -n "Checking if initialised..."
WAIT_COUNT=0
while [ ! -e config/config.ini.php ]; do
    WAIT_COUNT=$((WAIT_COUNT+1))
    if [ $WAIT_COUNT -gt $WAIT_MAX ]; then
        echo " timeout."
        exit 1
    fi
    echo -n .
    sleep $WAIT_STEP
done
echo " up."

exec "$@"
```

In docker-compose.yaml:
```
  cron:
    build: cron
    depends_on:
      - app
    volumes:
      - matomo:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - CRON_ARCHIVE=*/30 * * * *
      - CRON_TASKS=*/5 * * * *
    init: true
```
